presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "300m"
  - name: make-test
    decorate: true
    skip_report: false
    always_run: true
    context: thoth-station/prow/make-test
    spec:
      containers:
        - image: docker.io/golang:1.18
          command:
            - "make"
            - "test"
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
