# permissions for end users to edit customnbimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customnbimage-editor-role
rules:
- apiGroups:
  - meteor.zone
  resources:
  - customnbimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meteor.zone
  resources:
  - customnbimages/status
  verbs:
  - get
