# permissions for end users to view customnbimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customnbimage-viewer-role
rules:
- apiGroups:
  - meteor.zone
  resources:
  - customnbimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meteor.zone
  resources:
  - customnbimages/status
  verbs:
  - get
