---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-requirements
spec:
  params:
    - name: BASE_IMAGE
      type: string
    - description: Reference of the image buildah will produce.
      name: IMAGE
      type: string
    - default: >-
        registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: vfs
      description: Set buildah storage driver
      name: STORAGE_DRIVER
      type: string
    - default: "true"
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
      type: string
    - default: oci
      description: "The format of the built container, oci or docker"
      name: FORMAT
      type: string
  workspaces:
    - name: requirements
      readonly: true
      description: the list of pinned python package we install in the produced image
  volumes:
    - name: containers
      emptyDir: {}
  stepTemplate:
    image: $(params.BUILDER_IMAGE)
    command:
      - /usr/bin/buildah
    env:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: BUILDAH_FORMAT
        value: $(params.FORMAT)
    volumeMounts:
      - name: containers
        mountPath: /var/lib/containers
  steps:
    - args: ["from", "--name", "cnbi-image", "--tls-verify=$(params.TLSVERIFY)", "docker://$(params.BASE_IMAGE)"]
      name: from
    - args: ["copy", "cnbi-image", "$(workspaces.requirements.path)/requirements-pinned.txt", "/tmp/"]
      name: copy
    - args: ["run", "cnbi-image", "--", "pip", "install", "-r", "/tmp/requirements-pinned.txt"]
      name: run
    - args: ["commit", "cnbi-image", "$(params.IMAGE)"]
      name: commit
    - args: ["push", "--tls-verify=$(params.TLSVERIFY)", "$(params.IMAGE)"]
      name: push
