---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: cnbi-ubi8-py38-sample-1
spec:
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: cnbi-s2i-thoth-ubi8-py39-baseimage-sample-1
spec:
  runtimeEnvironment:
    baseImage: quay.io/thoth-station/s2i-thoth-ubi8-py39:v0.34.1
---
apiVersion: meteor.zone/v1alpha1
kind: CustomNBImage
metadata:
  name: cnbi-ubi8-py38-sample-2
spec:
  runtimeEnvironment:
    osName: ubi
    osVersion: "8"
    pythonVersion: "3.8"
  packageVersions:
    - "pandas"
